# Generated by Django 4.1.3 on 2022-11-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohtag_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_type', models.CharField(max_length=128)),
                ('donation_dis', models.TextField()),
                ('donation_cond', models.CharField(max_length=128)),
                ('donation_phone', models.CharField(max_length=10)),
            ],
        ),
    ]
